#
# SConscript
# Copyright (C) 2007 David M. Anderson
#
# SCons "makefile" for EpsilonDelta calendar library
#

Import( 'env' )
Import( 'useSTLport' )
if useSTLport:
    Import( 'stlportIncludeDir' )
Import( 'useBoost' )
if useBoost:
    Import( 'boostIncludeDir' )
Import( 'useLoki' )
if useLoki:
    Import( 'lokiIncludeDir' )

includePath = [ '.', '#astro', '#time', '#math', '#util', ]
if useSTLport:
    includePath.append( stlportIncludeDir )
if useBoost:
    includePath.append( boostIncludeDir )
if useLoki:
    includePath.append( lokiIncludeDir )

sources = [
            'CalendarLibText.cpp',
            'JulianCalendar.cpp',
            'JulianDate.cpp',
            'ISO8601Calendar.cpp',
            'ISO8601Date.cpp',
            'PersianWeek.cpp',
            'PersianAstronomicalCalendar.cpp',
            'PersianAstronomicalDate.cpp',
            'PersianArithmeticCalendar.cpp',
            'PersianArithmeticDate.cpp',
            'IslamicCalendar.cpp',
            'IslamicWeek.cpp',
            'IslamicDate.cpp',
            'HebrewCalendar.cpp',
            'HebrewWeek.cpp',
            'HebrewDate.cpp',
            'ChineseCalendar.cpp',
            'ChineseDate.cpp',
            'HinduWeek.cpp',
            'HinduAstro.cpp',
            'HinduSolarCalendar.cpp',
            'HinduSolarDate.cpp',
            'HinduLunisolarCalendar.cpp',
            'HinduLunisolarDate.cpp',
            'OldHinduSolarCalendar.cpp',
            'OldHinduSolarDate.cpp',
            'OldHinduLunisolarCalendar.cpp',
            'OldHinduLunisolarDate.cpp',
            'CopticCalendar.cpp',
            'CopticWeek.cpp',
            'CopticDate.cpp',
            'EthiopianCalendar.cpp',
            'EthiopianWeek.cpp',
            'EthiopianDate.cpp',
            'BahaiCalendar.cpp',
            'BahaiWeek.cpp',
            'BahaiDate.cpp',
            'BadiCalendar.cpp',
            'BadiDate.cpp',
            'EgyptianCalendar.cpp',
            'EgyptianDate.cpp',
            'ArmenianCalendar.cpp',
            'ArmenianWeek.cpp',
            'ArmenianDate.cpp',
            'MayanLongCountCalendar.cpp',
            'MayanLongCountDate.cpp',
            'MayanHaabCalendar.cpp',
            'MayanHaabDate.cpp',
            'MayanTzolkinCalendar.cpp',
            'FrenchRevolutionaryCalendar.cpp',
            'FrenchRevolutionaryDate.cpp'
          ]

lib = env.Library( 'EpsilonDelta_calendar', sources, CPPPATH = includePath )

Return( 'lib' )
