#ifndef CODEPOINTDATA_HPP
#define CODEPOINTDATA_HPP
/*
  CodePointData.hpp
  Copyright © 2009 David M. Anderson

  Unicode code point data. Generated by my UnicodeDB program.
*/


#include "StdInt.hpp"


namespace EpsilonDelta
{                                                      //namespace EpsilonDelta

//*****************************************************************************


extern int MaximumCodePoint;

enum ECharTypeBit
{
    CTB_Alpha       = (1 << 0),
    CTB_Upper       = (1 << 1),
    CTB_Lower       = (1 << 2),
    CTB_DecDigit    = (1 << 3),
    CTB_HexDigit    = (1 << 4),
    CTB_Punctuation = (1 << 5),
    CTB_Graph       = (1 << 6),
    CTB_Blank       = (1 << 7),
    CTB_Space       = (1 << 8),
    CTB_Ctrl        = (1 << 9)
};


extern uint16_t codePointCharTypes[ ];
extern wchar_t codePointToUpper[ ];
extern wchar_t codePointToLower[ ];
extern char codePointToASCII[ ];
extern uint8_t codePointLineBreakClasses[ ];


//*****************************************************************************

}                                                      //namespace EpsilonDelta
#endif //CODEPOINTDATA_HPP
