#
# SConscript
# Copyright (C) 2007 David M. Anderson
#
# SCons "makefile" for TestAstroLib.
#

Import( 'env' )
Import( 'compiler' )
Import( 'useSTLport' )
if useSTLport:
    Import( 'stlportIncludeDir' )
Import( 'useBoost' )
if useBoost:
    Import( 'boostIncludeDir' )

includePath = [ '.', '#astro', '#time', '#math', '#util' ]
if useSTLport:
    includePath.append( stlportIncludeDir )
if useBoost:
    includePath.append( boostIncludeDir )

libPath = '#'
libs = [ 'EpsilonDelta_astro', 'EpsilonDelta_time', 'EpsilonDelta_math',
         'EpsilonDelta_util' ]
if useSTLport:
    if ( compiler == 'gcc' ):
        libs.append( 'stlport_gcc' )

sources = [ 
            'TestAstroLib.cpp'
          ]

progs = []
prog = env.Program( 'TestAstroLib', sources, CPPPATH = includePath,
                    LIBS = libs, LIBPATH = libPath )
progs = progs + prog;

Return( 'progs' )
