#
# SConscript
# Copyright (C) 2007 David M. Anderson
#
# SCons "makefile" for TestUtilLib.
#

Import( 'env' )
Import( 'platform' )
Import( 'compiler' )
Import( 'useSTLport' )
if useSTLport:
    Import( 'stlportIncludeDir' )
Import( 'useBoost' )
if useBoost:
    Import( 'boostIncludeDir' )
Import( 'useLoki' )
if useLoki:
    Import( 'lokiIncludeDir' )

includePath = [ '.', '#util' ]
if ( useSTLport ):
    includePath.append( stlportIncludeDir )
if useBoost:
    includePath.append( boostIncludeDir )
if useLoki:
    includePath.append( lokiIncludeDir )

libPath = [ '#' ]
libs = [ 'EpsilonDelta_util' ]
if useSTLport:
    if ( compiler == 'gcc' ):
        libs.append( 'stlport_gcc' )
if useLoki:
    libs.append( 'Loki' )

sources = [ 
            'TestUtilLib.cpp'
          ]

progs = []
prog = env.Program( 'TestUtilLib', sources, CPPPATH = includePath,
                    LIBS = libs, LIBPATH = libPath )
progs = progs + prog;

Return( 'progs' )
